// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts
// @ts-nocheck
// biome-ignore-all lint: generated upstream protocol source
// biome-ignore-all assist/source/organizeImports: generated upstream protocol source
/**
 * Adds a duration to an ISO 8601 timestamp and returns the result in canonical
 * ISO 8601 form.
 */
export function addMillisecondsToTimestamp(timestamp: string, duration: number): string {
  return new Date(Date.parse(timestamp) + duration).toISOString();
}
