// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts
// @ts-nocheck
// biome-ignore-all lint: generated upstream protocol source
// biome-ignore-all assist/source/organizeImports: generated upstream protocol source
/**
 * Error Codes — Aggregator shim that re-exports error declarations from
 * their canonical location.
 *
 * @module errors
 */

export * from "./common/errors.js";
