// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts
// @ts-nocheck
// biome-ignore-all lint: generated upstream protocol source
// biome-ignore-all assist/source/organizeImports: generated upstream protocol source
/**
 * Message Types — Aggregator shim that re-exports message declarations from
 * their canonical location.
 *
 * @module messages
 */

export * from "./common/messages.js";
