// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts
// @ts-nocheck
// biome-ignore-all lint: generated upstream protocol source
// biome-ignore-all assist/source/organizeImports: generated upstream protocol source
/**
 * Notification Types — Aggregator shim that re-exports channel-organized
 * notification declarations. New code should import directly from the
 * per-channel files under `types/common/` and `types/channels-root/`.
 *
 * @module notifications
 */

export * from "./common/notifications.js";
export * from "./channels-root/notifications.js";
export * from "./channels-otlp/notifications.js";
