// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts
// @ts-nocheck
// biome-ignore-all lint: generated upstream protocol source
// biome-ignore-all assist/source/organizeImports: generated upstream protocol source

export const AHP_SOURCE_COMMIT = "7ed423d" as const;
export const AHP_SOURCE_REPOSITORY = "agent-host-protocol" as const;
const AHP_SOURCE_TYPES_ROOT = "../agent-host-protocol" as const;
const AHP_SOURCE_TYPES_SUFFIX = "types" as const;
export const AHP_SOURCE_TYPES_PATH: string = `${AHP_SOURCE_TYPES_ROOT}/${AHP_SOURCE_TYPES_SUFFIX}`;
export const AHP_GENERATED_FILES = [
  "state.ts",
  "actions.ts",
  "action-origin.generated.ts",
  "reducers.ts",
  "commands.ts",
  "notifications.ts",
  "messages.ts",
  "errors.ts",
  "version/registry.ts",
] as const;
