// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts

export const AHP_SOURCE_COMMIT = "5f79fe4" as const;
export const AHP_SOURCE_REPOSITORY = "agent-host-protocol" as const;
export const AHP_SOURCE_TYPES_PATH = "../agent-host-protocol/types" as const;
export const AHP_GENERATED_FILES = [
  "state.ts",
  "actions.ts",
  "action-origin.generated.ts",
  "reducers.ts",
  "commands.ts",
  "notifications.ts",
  "messages.ts",
  "errors.ts",
  "version/registry.ts",
] as const;
