import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const AHP_ROOT = path.resolve(ROOT, "../agent-host-protocol");
const TYPES_DIR = path.join(AHP_ROOT, "types");
const DEST_ROOT = path.join(ROOT, "packages/protocol");
const DEST_SRC = path.join(DEST_ROOT, "src");
const FIXTURE_SRC = path.join(TYPES_DIR, "test-cases/reducers");
const FIXTURE_DEST = path.join(DEST_ROOT, "test-cases/reducers");
const BANNER =
  "// DO NOT EDIT -- auto-generated by scripts/sync-agent-host-protocol.ts\n// @ts-nocheck\n// biome-ignore-all lint: generated upstream protocol source\n// biome-ignore-all assist/source/organizeImports: generated upstream protocol source\n";

const PROTOCOL_FILES = [
  "state.ts",
  "actions.ts",
  "action-origin.generated.ts",
  "reducers.ts",
  "commands.ts",
  "notifications.ts",
  "messages.ts",
  "errors.ts",
  "version/registry.ts",
] as const;

function ensureInside(baseDir: string, candidate: string): void {
  const base = path.resolve(baseDir);
  const resolved = path.resolve(candidate);
  if (resolved !== base && !resolved.startsWith(`${base}${path.sep}`)) {
    throw new Error(`Refusing to access path outside ${base}: ${resolved}`);
  }
}

function requireFile(filePath: string): void {
  if (!existsSync(filePath)) {
    throw new Error(`Required AHP source file is missing: ${filePath}`);
  }
}

function getSourceCommitHash(): string {
  return execFileSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: AHP_ROOT,
    encoding: "utf8",
  }).trim();
}

function copyProtocolFile(relPath: string): void {
  const source = path.resolve(TYPES_DIR, relPath);
  const destination = path.resolve(DEST_SRC, relPath);

  ensureInside(TYPES_DIR, source);
  ensureInside(DEST_SRC, destination);
  requireFile(source);

  mkdirSync(path.dirname(destination), { recursive: true });
  const content = readFileSync(source, "utf8");
  writeFileSync(destination, `${BANNER}${content}`, "utf8");
}

function copyReducerFixtures(): void {
  if (!existsSync(FIXTURE_SRC)) {
    throw new Error(`Required AHP reducer fixture directory is missing: ${FIXTURE_SRC}`);
  }

  rmSync(FIXTURE_DEST, { recursive: true, force: true });
  mkdirSync(FIXTURE_DEST, { recursive: true });

  const fixtureFiles = readdirSync(FIXTURE_SRC)
    .filter((name) => name.endsWith(".json"))
    .sort();

  if (fixtureFiles.length === 0) {
    throw new Error(`No reducer fixture JSON files found in ${FIXTURE_SRC}`);
  }

  for (const fileName of fixtureFiles) {
    const source = path.resolve(FIXTURE_SRC, fileName);
    const destination = path.resolve(FIXTURE_DEST, fileName);

    ensureInside(FIXTURE_SRC, source);
    ensureInside(FIXTURE_DEST, destination);
    requireFile(source);

    writeFileSync(destination, readFileSync(source, "utf8"), "utf8");
  }
}

function writeSourceInfo(commitHash: string): void {
  const sourceInfoPath = path.join(DEST_SRC, "source-info.ts");
  const generatedFiles = [...PROTOCOL_FILES];
  const source = `${BANNER}
export const AHP_SOURCE_COMMIT = ${JSON.stringify(commitHash)} as const;
export const AHP_SOURCE_REPOSITORY = "agent-host-protocol" as const;
const AHP_SOURCE_TYPES_ROOT = "../agent-host-protocol" as const;
const AHP_SOURCE_TYPES_SUFFIX = "types" as const;
export const AHP_SOURCE_TYPES_PATH: string = \`\${AHP_SOURCE_TYPES_ROOT}/\${AHP_SOURCE_TYPES_SUFFIX}\`;
export const AHP_GENERATED_FILES = ${JSON.stringify(generatedFiles, null, 2)} as const;
`;

  writeFileSync(path.join(DEST_ROOT, ".ahp-version"), `${commitHash}\n`, "utf8");
  writeFileSync(sourceInfoPath, source, "utf8");
}

function main(): void {
  if (!existsSync(TYPES_DIR)) {
    throw new Error(
      `Cannot find ${TYPES_DIR}. Clone agent-host-protocol as a sibling of this repo.`,
    );
  }

  mkdirSync(DEST_SRC, { recursive: true });

  for (const relPath of PROTOCOL_FILES) {
    copyProtocolFile(relPath);
  }

  copyReducerFixtures();
  writeSourceInfo(getSourceCommitHash());

  execFileSync(
    "pnpm",
    [
      "exec",
      "biome",
      "format",
      "--write",
      "packages/protocol/src",
      "packages/protocol/test-cases/reducers",
    ],
    { cwd: ROOT, stdio: "inherit" },
  );
}

main();
