// Compatibility re-export backed by generated @ahp-inspector/protocol.
// New protocol consumers should import canonical names directly from
// @ahp-inspector/protocol; this subpath keeps older shared callers compiling.
export type {
  ActionEnvelope,
  ActionEnvelope as IActionEnvelope,
  ActionType,
  AhpClientNotification,
  AhpClientNotification as IAhpClientNotification,
  AhpNotification,
  AhpNotification as IAhpNotification,
  AhpRequest,
  AhpRequest as IAhpRequest,
  AhpResponse,
  AhpResponse as IAhpResponse,
  AhpServerNotification,
  AhpServerNotification as IAhpServerNotification,
  AhpSuccessResponse,
  AhpSuccessResponse as IAhpSuccessResponse,
  AuthRequiredReason,
  ClientNotificationMap,
  ClientNotificationMap as IClientNotificationMap,
  CommandMap,
  CommandMap as ICommandMap,
  JsonRpcErrorResponse,
  JsonRpcErrorResponse as IJsonRpcErrorResponse,
  JsonRpcNotification,
  JsonRpcNotification as IJsonRpcNotification,
  JsonRpcRequest,
  JsonRpcRequest as IJsonRpcRequest,
  JsonRpcResponse,
  JsonRpcResponse as IJsonRpcResponse,
  JsonRpcSuccessResponse,
  JsonRpcSuccessResponse as IJsonRpcSuccessResponse,
  NotificationMap,
  NotificationMap as INotificationMap,
  NotificationType,
  ProtocolMessage,
  ProtocolMessage as IProtocolMessage,
  ProtocolNotification,
  ProtocolNotification as IProtocolNotification,
  ServerNotificationMap,
  ServerNotificationMap as IServerNotificationMap,
} from "@ahp-inspector/protocol";
